site_name: "ToDo List"
site_url: https://alliciarocha.github.io/proj-exten/
repo_url: https://github.com/alliciarocha/proj-exten
site_description: Documentação do gerenciador de tarefas MVC
site_author: Allicia

nav:
  - Início: index.md
  - Arquitetura: architecture.md
  - Uso: usage.md
  - Implantação: deployment.md

theme:
  name: material
  language: pt-BR
  palette:
    - scheme: default
      primary: purple
      accent: amber

plugins: []
